---
title: "network_meta-analysis"
author: "Dong Woon Kim, M.D."
date: "2026-08-01"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r setup}

setwd("G:/My Drive/github/d-wkim/network_meta-analysis/")

packages <- c(
  "googledrive",
  "googlesheets4",
  "readxl",
  "metafor",
  "dplyr",
  "meta",
  "ggplot2",
  "ggpubr",
  "ggforestplot",
  "ggplotify",
  "ggplot2",
  "tidyverse",
  "devtools",
  "netmeta",
  "rgl"
)


# install.packages(packages, dependencies = TRUE)

devtools::install_github("NightingaleHealth/ggforestplot")
lapply(packages, library, character.only = TRUE)
```

```{r}

# Custom R function for running network meta-analysis 

network_meta_analysis <- function(df) {
  
  data_path <- paste0("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/",df, ".csv")
  data <- read_csv(data_path)
  
  m.netmeta <- netmeta(
		TE = smd, 
		seTE = se,
		treat1 = treat1,
		treat2 = treat2,
		studlab = study,
		data = data,
		sm = "SMD",
		common = FALSE, 
		random = TRUE,
		reference.group = "BPTB",
		details.chkmultiarm = TRUE,
		sep.trts = " vs "
	)

	txt = paste0("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/", df, ".txt")

	# Print and save network meta-analysis results
	
	sink(file = txt)
	print(m.netmeta)

	labels = m.netmeta$trts
	
	long.labels = c("Bone-patellar tendon-bone", "Hamstring", "Peroneus longus", "Quadriceps", "Tibialis anterior")
	svg = paste0("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/", df, ".svg")
	svg(file = svg, height = 5, width = 5)

	network_graph = netgraph(m.netmeta, labels = labels, dim = "2d", scale = 1.1)
	print(network_graph)
	dev.off()
	
  return(m.netmeta)	
	
}

```

```{r}

df = c("ikdc_subjective", 
       "lysholm", 
       "tegner", 
       "instrumented_laxity", 
       "pivot_shift_1", 
       "pivot_shift_2", 
       "lachman_1", 
       "lachman_2", 
       "graft_failure"
       )


lapply(df, network_meta_analysis)

ikdc_subjective <- network_meta_analysis("ikdc_subjective")
lysholm <- network_meta_analysis("lysholm")

```



```{r ikdc_subjective}

ikdc_subjective <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/ikdc_subjective.csv")

m.netmeta <- netmeta(
  TE = smd,
  seTE = se,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = ikdc_subjective,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/ikdc_subjective.txt")
print(m.netmeta)

labels = m.netmeta$trts
long.labels = c("Bone-patellar tendon-bone", "Hamstring", "Peroneus longus", "Quadriceps", "Tibialis anterior")

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/ikdc_subjective.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()
# forest plots for network meta-analysis

#svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/continuous/ikdc_subjective.svg", width = 9, height = 10)
print(network_graph)

forest(m.netmeta,
       reference.group = "BPTB",
       sortvar = TE,
       xlim = c(-1.5, 0.5),
       smlab = paste("BPTB vs other grafts \n",
                     "(IKDC subjective)"),
       drop.reference.group = TRUE,
       labels = long.labels)

#dev.off()
svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/lattice/ikdc_subjective.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()

```

```{r lysholm}

lysholm <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/lysholm.csv")

m.netmeta <- netmeta(
  TE = smd,
  seTE = se,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = lysholm,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/lysholm.txt")
print(m.netmeta)

labels = m.netmeta$trts
svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/lysholm.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/lysholm.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()
```

```{r tegner}

tegner <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/tegner.csv")

m.netmeta <- netmeta(
  TE = smd,
  seTE = se,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = tegner,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/tegner.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")

# Network graph
svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/tegner.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/tegner.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()

```

```{r instrumented_laxity}
instrumented_laxity <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/instrumented_laxity.csv")

instrumented_laxity <- na.omit(instrumented_laxity)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = instrumented_laxity,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/instrumented_laxity.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")

# Network graph
svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/instrumented_laxity.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)

dev.off()
# Forest plot
svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/instrumented_laxity.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()
```

```{r pivot_shift_1}

pivot_shift_1 <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/pivot_shift_1.csv")

pivot_shift_1 <- na.omit(pivot_shift_1)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se_smd,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = pivot_shift_1,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/pivot_shift_1.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")


svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/pivot_shift_1.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()
```

```{r pivot_shift_2}

pivot_shift_2 <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/pivot_shift_2.csv")
pivot_shift_2 <- na.omit(pivot_shift_2)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se_smd,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = pivot_shift_2,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/pivot_shift_2.txt")
print(m.netmeta)
sink()

labels = m.netmeta$trts
#install.packages("rgl")

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/pivot_shift_2.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()

```


```{r lachman_1}

lachman_1 <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/lachman_1.csv")
lachman_1 <- na.omit(lachman_1)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se_smd,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = lachman_1,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/lachman_1.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/lachman_1.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)

print(network_graph)
dev.off()

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/lachman_1.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()

```


```{r lachman_2}

lachman_2 <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/lachman_2.csv")

lachman_2 <- na.omit(lachman_2)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se_smd,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = lachman_2,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/lachman_2.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/lachman_2.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/lachman_2.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()
```

```{r graft_failure}

graft_failure <- read_csv("G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/sheets_for_analysis/graft_failure_analysis.csv")

graft_failure <- na.omit(graft_failure)

m.netmeta <- netmeta(
  TE = smd,
  seTE = se_smd,
  treat1 = treat1,
  treat2 = treat2,
  studlab = study,
  data = graft_failure,
  sm = "SMD",
  common = FALSE,
  random = TRUE,
  reference.group = "BPTB",
  details.chkmultiarm = TRUE,
  sep.trts = " vs "
)

sink(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/analysis/results/graft_failure.txt")
print(m.netmeta)

labels = m.netmeta$trts
#install.packages("rgl")

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/R/plots/network_graph/graft_failure.svg", height = 5, width = 5)

network_graph = netgraph(m.netmeta, labels = labels,
         dim = "2d",
         scale = 1.1)
print(network_graph)
dev.off()

svg(file = "G:/My Drive/github/d-wkim/network_meta-analysis/3_meta-analysis/plots/lattice/graft_failure.svg", height = 10, width = 10)
lattice <- netsplit(m.netmeta) %>% forest() 
print(lattice)
dev.off()


```

```{r}



```